# Generated by Django 5.2 on 2025-06-05 16:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duty_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ImportSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin', models.CharField(max_length=100)),
                ('value_cif', models.DecimalField(decimal_places=2, help_text='Valeur CIF ou valeur en douane (VD)', max_digits=12)),
                ('moyen_transport', models.CharField(choices=[('maritime', 'Maritime'), ('aerien', 'Aérien'), ('terrestre', 'Terrestre')], max_length=20)),
                ('value_fret', models.DecimalField(decimal_places=2, help_text='Coût du transport international (FRET)', max_digits=12)),
                ('is_origin_cemac', models.BooleanField(default=True, help_text='Exonération du DD si origine CEMAC')),
                ('total_duties', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total des droits et taxes', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('legal_status', models.CharField(choices=[('physique', 'Personne physique'), ('morale', 'Personne morale')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DutiesBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Droit de Douane')),
                ('da', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Droit d'Accise")),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVA')),
                ('cac', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CAC')),
                ('pct', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PCT')),
                ('dao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='DAO')),
                ('ri', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Redevence Informatique')),
                ('tci', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TCI')),
                ('cia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CIA')),
                ('ohada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prélèvement OHADA')),
                ('prd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PRD')),
                ('taxe_phytosanitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxe Phytosanitaire')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duties_detail', to='api.importsimulation')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='importsimulation',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.product'),
        ),
        migrations.AddField(
            model_name='importsimulation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='api.userinfo'),
        ),
    ]
